- src/main/java/com/example/demo/ai/controller/GptAssistantTestController.java
- src/main/java/com/example/demo/ai/dto/run/CreateRunReqDto.java
- src/main/java/com/example/demo/ai/dto/run/CreateRunResDto.java
- src/main/java/com/example/demo/ai/service/GptAssistantService.java
- run 객체 생성 메서드
비동기로 처리되는 형태라 `status` 값을 통해 완료 여부 체크
아래는 가능한 상태 목록 입니다.
`queued`, `in_progress`, `requires_action`, `cancelling`, `cancelled`, `failed`, `completed`, or `expired`.
> Feat(ai):assistant run 객체 생성 메서드

- src/main/java/com/example/demo/ai/AppConstants.java
- src/main/java/com/example/demo/ai/controller/GptAssistantTestController.java
- src/main/java/com/example/demo/ai/dto/CreateThreadReqDto.java
- src/main/java/com/example/demo/ai/dto/CreateThreadResDto.java
- src/main/java/com/example/demo/ai/dto/GetModelsResDto.java
- src/main/java/com/example/demo/ai/dto/assistant/CreateAssistantReqDto.java
- src/main/java/com/example/demo/ai/dto/assistant/CreateAssistantResDto.java
- src/main/java/com/example/demo/ai/dto/assistant/GetAssistantResDto.java
- src/main/java/com/example/demo/ai/dto/message/CreateMessageReqDto.java
- src/main/java/com/example/demo/ai/dto/message/CreateMessageResDto.java
- src/main/java/com/example/demo/ai/dto/thread/CreateThreadReqDto.java
- src/main/java/com/example/demo/ai/dto/thread/CreateThreadResDto.java
- src/main/java/com/example/demo/ai/entity/Assistant.java
- src/main/java/com/example/demo/ai/entity/AssistantThread.java
- src/main/java/com/example/demo/ai/entity/AssistantThreadMessage.java
- src/main/java/com/example/demo/ai/repo/AssistantRepo.java
- src/main/java/com/example/demo/ai/repo/AssistantThreadRepo.java
- src/main/java/com/example/demo/ai/service/GptAssistantService.java
- src/main/resources/application-dev-example.yaml
- src/main/resources/data.sql
- `assistant` 생성 메서드 
- `assistant thread` 생성 메서드
- assistant 관련 `entity` 생성
- `assistant message` 생성 메서드
- `run` 생성 메서드
`thread` 관련 처리 중 생성된 스레드를 리스트 형태로 볼 수 있는,
API를 openAI에서 따로 제공하고 있지 않아 DB에서 직접 관리 해야함.
> Feat(ai): assistant 생성 메서드, 스레드 생성 메서드 구현

- src/main/java/com/example/demo/ai/controller/GptAssistantTestController.java
- src/main/java/com/example/demo/ai/dto/message/CreateMessageResDto.java
- src/main/java/com/example/demo/ai/dto/message/GetMessagesResDto.java
- src/main/java/com/example/demo/ai/service/GptAssistantService.java
- 메시지 조회 메서드 ( 실행 결과 확인 )
- 실행 결과가 비동기로 처리되어서 별도의 처리가 필요함
> Feat: 어시스턴트 메시지 기능 구현

- build.gradle
- src/main/java/com/example/demo/auth/config/WebSecurityConfig.java
- src/main/java/com/example/demo/jwt/JwtTokenFilter.java
- src/main/java/com/example/demo/jwt/JwtTokenUtils.java
- src/main/java/com/example/demo/oauth/OAuth2SuccessHandler.java
- src/main/java/com/example/demo/oauth/OAuth2UserService.java
- Security Config
- security, jwt 설정 및 카카오 api 기본 설정
- 시큐리티, jwt, 카카오 api 설정 후 로컬 테스트는 끝났습니다. user crud 완성 후 재 테스트 해볼게요!
스크린샷을 첨부해주세요.
- 관련 이슈를 입력해주세요.
> Security config

- src/main/java/com/example/demo/ai/controller/GptAssistantTestController.java
- src/main/java/com/example/demo/ai/dto/message/CreateMessageDto.java
- src/main/java/com/example/demo/ai/dto/message/CreateMessageResDto.java
- src/main/java/com/example/demo/ai/dto/message/CreateThreadAndRunReqDto.java
- src/main/java/com/example/demo/ai/dto/message/CreateThreadAndRunResDto.java
- src/main/java/com/example/demo/ai/service/GptAssistantService.java
- 신규 회원 가입시 해당 유저의 스레드와 카테고리를 추천해줘야함
- Dto 이름 변경
- `createThreadAndRun` 메서드 생성
> Feat(ai): 스레드 생성 즉시 실행 하는 메서드

- src/main/java/com/example/demo/ai/controller/GptAssistantTestController.java
- src/main/java/com/example/demo/ai/dto/message/CreateMessageDto.java
- src/main/java/com/example/demo/ai/dto/message/CreateMessageResDto.java
- src/main/java/com/example/demo/ai/dto/message/CreateThreadAndRunReqDto.java
- src/main/java/com/example/demo/ai/dto/message/CreateThreadAndRunResDto.java
- src/main/java/com/example/demo/ai/dto/thread/DeleteThreadResDto.java
- src/main/java/com/example/demo/ai/entity/Assistant.java
- src/main/java/com/example/demo/ai/entity/AssistantThread.java
- src/main/java/com/example/demo/ai/repo/AssistantRepo.java
- src/main/java/com/example/demo/ai/repo/AssistantThreadRepo.java
- src/main/java/com/example/demo/ai/service/GptAssistantLifeCycleService.java
- src/main/java/com/example/demo/ai/service/GptAssistantService.java
- src/main/java/com/example/demo/ai/service/dto/DeleteAssistantResDto.java
- src/main/resources/data.sql
- 어시스턴트 버전 관리 및 확장성 고려
- 어시스턴트 생성시 이를 DB에 동기화 하는 메서드 구현
- 스레드 생성시 이를 DB에 동기화 하는 메서드 구현
- 동기화 실패시 처리할 메서드 구현
- 동기화 실패시 어시스턴트를 다시 삭제하는 로직이 있는데, 삭제 요청도 실패하면 어떻게 할지 고민해봐야함
> Feat(lifeCycle): 어시스턴트 동기화 및 실패 처리

- src/main/java/com/example/demo/ai/dto/SyncDto.java
- src/main/java/com/example/demo/ai/dto/thread/CreateThreadResDto.java
- src/main/java/com/example/demo/ai/service/GptAssistantCoreService.java
- src/main/java/com/example/demo/ai/service/GptAssistantService.java
- 동기화 결과를 명시적으로 반환하기위함
- 동기화 결과를 명시적으로 반환함 `created` `deleted` `updated`
> fix: 동기화 작업시 결과를 나타내는 dto생성

- src/main/java/com/example/demo/auth/AuthenticationFacade.java
- src/main/java/com/example/demo/user/controller/UserController.java
- src/main/java/com/example/demo/user/dto/UserDto.java
- src/main/java/com/example/demo/user/entity/CustomUserDetails.java
- src/main/java/com/example/demo/user/entity/User.java
- src/main/java/com/example/demo/user/repo/UserRepo.java
- src/main/java/com/example/demo/user/service/JpaUserDetailsManager.java
- src/main/java/com/example/demo/user/service/UserService.java
> Feat(user): 유저 도메인 관련 코드

- src/main/java/com/example/demo/ai/entity/AssistantThread.java
- src/main/java/com/example/demo/ai/repo/AssistantThreadRepo.java
- src/main/java/com/example/demo/ai/service/GptAssistantCoreService.java
- src/main/java/com/example/demo/ai/service/GptAssistantService.java
- 스레드 DB 저장 메서드 구현
- 스레드 정보 가져오는 메서드 구현
- 스레드 동기화 메서드 수정
동기화 후 이전에 생성되었던 항목을 삭제하는 로직이 필요함
> Fix(ai): 스레드 동기화 메서드 수정

- src/main/resources/templates/home.html
- 날씨 뉴스 화면에 표시 
- 지도상에 검색 결과 지역의 장소를 마커로 표시
> Feat: 오늘의 날씨 뉴스 표시, 지역 검색 마커 표시

- src/main/java/com/example/demo/ai/controller/GptAssistantTestController.java
- src/main/java/com/example/demo/ai/dto/run/OneStepRunParamDto.java
- src/main/java/com/example/demo/ai/dto/run/OneStepRunReqDto.java
- src/main/java/com/example/demo/ai/entity/Assistant.java
- src/main/java/com/example/demo/ai/service/GptAssistantApiService.java
- 메시지 리스트 조회 메서드 구현
- 스레드 생성 -> 메시지 생성 -> 실행 과정 없이 하나의 요청으로 실행 가능한 기능 구현
- 메시지 생성시 및 저장시 접미사 붙히도록 수정
> Feat(assistant): 어시스턴트 사용 API 기능 구현

- src/main/java/com/example/demo/ai/AppConstants.java
- src/main/java/com/example/demo/ai/controller/GptAssistantTestController.java
- src/main/java/com/example/demo/ai/dto/Tool.java
- src/main/java/com/example/demo/ai/dto/assistant/CreateAssistantReqDto.java
- src/main/java/com/example/demo/ai/dto/assistant/GptApiCreateAssistantReqDto.java
- src/main/java/com/example/demo/ai/dto/assistant/GptApiCreateAssistantResDto.java
- src/main/java/com/example/demo/ai/dto/run/CreateRunResDto.java
- src/main/java/com/example/demo/ai/entity/Assistant.java
- src/main/java/com/example/demo/ai/repo/AssistantRepo.java
- src/main/java/com/example/demo/ai/service/GptAssistantApiService.java
- src/main/java/com/example/demo/ai/service/GptService.java
- 어시스턴트 중복생성 방지 ( DB에 있으면 신규 생성 안하지만 DB 초기화 하고 다시 시작하면 똑같이 재생성함 )
- 어시스턴트 파일 검색 옵션, 응답 카테고리 한글로 주도록 설정
> Fix(assistant): 어시스턴트 중복 생성 방지, 파일 검색 옵션 추가

- build.gradle
- src/main/java/com/example/demo/community/config/WebMvcConfig.java
- src/main/java/com/example/demo/community/service/PostService.java
- src/main/resources/templates/ootd.html
- feat/community
- 파일 업로드 시 이미지 즉시 반영
- 정적 리소스 경로 설정
- > gradle :  추가
implementation 'org.springframework.boot:spring-boot-devtools' 
- > WebMvcConfig 설정
- design : 게시판 형식에서 이미지가 보여질 수 있게 카드형 으로 front 수정
> Fix(community) : img upload 후 img즉시 반영

- src/main/java/com/example/demo/ai/AppConstants.java
- src/main/java/com/example/demo/ai/controller/GptAssistantTestController.java
- src/main/java/com/example/demo/ai/dto/assistant/Assistant.java
- src/main/java/com/example/demo/ai/dto/assistant/AssistantList.java
- src/main/java/com/example/demo/ai/service/GptAssistantApiService.java
- src/main/java/com/example/demo/ai/service/GptAssistantClientConfig.java
- src/main/java/com/example/demo/ai/service/GptAssistantService.java
- 중복 생성으로 버전 관리가 어려워짐
- 중복생성 방지 로직
> Fix(Assistant): 어시스턴트 생성 중복 방지

- src/main/java/com/example/demo/user/repo/JpaUserDetailsManager.java
임시방편으로 에러 수정 추후에 최종 수정 예정
- userCRUD
- 에러 임시로 수정
- 주요 변경사항 목록을 알려주세요.
스크린샷을 첨부해주세요.
- 관련 이슈를 입력해주세요.
> fix: UserDetailsManager error

- .github/workflows/gradle.yml
> Feat(ci/cd): Create gradle.yml

- Dockerfile
> Deploy: Dockerfile 추가

- src/main/resources/static/css/home.css
- src/main/resources/static/js/region-search.js
- src/main/resources/static/js/weather-info.js
- src/main/resources/templates/home.html
- 날씨 아이콘의 크기를 작게 조절 / 오늘의 날씨 아이콘 추가
- `지역 검색` 버튼 클릭 시 모달 창 기능 활성화
> feat(front): 날씨 아이콘 크기 조절, 지역 검색 modal 구현

- src/main/java/com/example/demo/ai/AppConstants.java
- src/main/java/com/example/demo/ai/service/GptService.java
- src/main/java/com/example/demo/scheduler/SchedulerKR.java
> fix: 스케줄러 버그 수정

- src/main/java/com/example/demo/mypage/service/MyPageService.java
- src/main/java/com/example/demo/oauth/OAuth2SuccessHandler.java
- src/main/java/com/example/demo/user/service/UserService.java
- src/main/resources/templates/mypage.html
카카오 로그인 후 마이페이지 접속 에러 수정
- UserCRUD
- 마이페이지 접속 에러 수정
- 주요 변경사항 목록을 알려주세요.
스크린샷을 첨부해주세요.
- 관련 이슈를 입력해주세요.
> fix: fix kakao login error
